apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.name }}-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: {{ $.Values.port }}
      targetPort: {{ $.Values.port }}
      protocol: TCP
  selector:
    app: {{ $.Values.name }}
