apiVersion: v1
kind: Service
metadata:
  name: react-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: react
